import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useQuery } from "@apollo/client";
import recommendedProfilesQuery from "./gql/recommendProfiles.js";
import Profile from "../components/Profile.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { loading, error, data } = useQuery(recommendedProfilesQuery);

  if (loading) return "Loading..";
  if (error) return `Error! ${error.message}`;
  return (
    <>
      <Head>
        <title>Dapp with Lens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {data.recommendedProfiles.map((profile, index) => {
            return (
              <Profile
                key={profile.id}
                profile={profile}
                displayFullProfile={false}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}
